---
- name: Enable manage sudo for ldap users by sudorules
  lineinfile:
    path: /etc/nsswitch.conf
    line: "sudoers:	files sss"
  when: sssd_ldap_sudo

- name: Query SSSD in nsswitch.conf
  replace:
    dest: /etc/nsswitch.conf
    regexp: '^({{ item }}(?!.*\bsss\b).*)$'
    replace: '\1 sss'
    backup: yes
  with_items:
    - passwd
    - shadow
    - group
    - services
    - netgroup
    - automount
  when: ansible_os_family == "Debian"
...

